# Generated by Django 3.1.8 on 2021-04-06 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.GenericIPAddressField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('order_id', models.CharField(max_length=15)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
    ]
