# Generated by Django 3.1.8 on 2021-04-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='address',
            new_name='ip_address',
        ),
    ]
