# Generated by Django 3.1.8 on 2021-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0002_auto_20210406_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
