# Generated by Django 3.1.8 on 2021-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0003_buyer_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
